### ISSUE TITLE
Memory access fault

### ISSUE THREAD

**Issue by matsujirushi** [FreeRTOS/Lab-Project-FreeRTOS-Cellular-Library#19]
There are memory access fault when call Cellular_Init() at no SIM.

https://github.com/FreeRTOS/Lab-Project-FreeRTOS-Cellular-Library/blob/main/common/src/cellular_pktio.c#L346

pRespPrefix was NULL.

**Comment by chinglee-iot** [comment]
Hi Matsujirushi,

This issue is related to #16 .
Thank you for your feedback.

**Comment by chinglee-iot** [comment]
#22 Fix this issue as well as pContext->pCurrentCmd.
Thank you for your feedback.
