### ISSUE TITLE
Queue created by _Cellular_PktHandlerInit is not deleted during cleanup.

### ISSUE THREAD

**Issue by jgeertsema** [FreeRTOS/Lab-Project-FreeRTOS-Cellular-Library#2]
When testing our code we noticed a 96 byte memory leak when initializing/deinitializing the cell library. I tracked it down to the 96 bytes that is malloced when it's creating the queue (pktRespQueue) by calling _Cellular_PktHandlerInit. The function  _Cellular_PktHandlerCleanup is written to remove this queue, but it is only called by libOpen if it fails to initialize. I've added _Cellular_PktHandlerCleanup to line 324 in the function libClose to correct the issue. 

![image](https://user-images.githubusercontent.com/59580831/106196141-11110100-617f-11eb-87be-e562218af5c4.png)

**Comment by chinglee-iot** [comment]
Thank you for your reply. We will verify this issue and update it soon.

**Comment by chinglee-iot** [comment]
Thank you for pointing this out. The patch is merged.
Please let us know if you have any further question about this library.
